.TH "C:/Users/user/Desktop/irreducible-polynomial-doc/irreducible-polynomial-doc/source/driver Directory Reference" 3 "Fri Apr 29 2016" "Irreducible Polynomial" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Desktop/irreducible-polynomial-doc/irreducible-polynomial-doc/source/driver Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdriver\&.cpp\fP"
.br
.RI "\fIФайл с реализацием методов класса \fBDriver\fP\&. \fP"
.ti -1c
.RI "file \fBdriver\&.h\fP"
.br
.RI "\fIЗаголовочный файл класса \fBDriver\fP\&. \fP"
.in -1c
