.TH "C:/Users/user/Desktop/irreducible-polynomial-doc/source/driver/LibraryInterface Directory Reference" 3 "Fri Apr 29 2016" "Irreducible Polynom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Desktop/irreducible-polynomial-doc/source/driver/LibraryInterface Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBLibraryInterface\&.cpp\fP"
.br
.RI "\fIФайл с реализацием методов класса \fBLibraryInterface\fP\&. \fP"
.ti -1c
.RI "file \fBLibraryInterface\&.h\fP"
.br
.RI "\fIЗаголовочный файл класса \fBLibraryInterface\fP\&. \fP"
.in -1c
