.TH "C:/Users/user/Desktop/irreducible-polynomial-doc/irreducible-polynomial-doc/source/driver/Config Directory Reference" 3 "Fri Apr 29 2016" "Irreducible Polynomial" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Desktop/irreducible-polynomial-doc/irreducible-polynomial-doc/source/driver/Config Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.in -1c
