.TH "C:/Users/user/Desktop/irreducible-polynomial-doc/source/lib/Polynom Directory Reference" 3 "Fri Apr 29 2016" "Irreducible Polynom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Desktop/irreducible-polynomial-doc/source/lib/Polynom Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpolynom\&.cpp\fP"
.br
.RI "\fIФайл с реализацией методов класса \fBPolynom\fP и перегрузкой операторов \fP"
.ti -1c
.RI "file \fBpolynom\&.h\fP"
.br
.RI "\fIЗаголовочный файл класса \fBPolynom\fP\&. \fP"
.in -1c
