.TH "C:/Users/user/Desktop/irreducible-polynomial-doc/source/lib/Scheduler Directory Reference" 3 "Fri Apr 29 2016" "Irreducible Polynom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Desktop/irreducible-polynomial-doc/source/lib/Scheduler Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBscheduler\&.cpp\fP"
.br
.RI "\fIФайл содержащий описание методов класса 'планировщик'\&. \fP"
.ti -1c
.RI "file \fBscheduler\&.h\fP"
.br
.RI "\fIЗаголовчный файл с описанием класса 'планировщик'\&. \fP"
.in -1c
