.TH "C:/Users/user/Desktop/irreducible-polynomial-doc/irreducible-polynomial-doc/source/driver/driver.cpp" 3 "Fri Apr 29 2016" "Irreducible Polynomial" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Desktop/irreducible-polynomial-doc/irreducible-polynomial-doc/source/driver/driver.cpp \- Файл с реализацием методов класса \fBDriver\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include 'LibraryInterface/LibraryInterface\&.h'\fP
.br
\fC#include 'Config/config\&.h'\fP
.br
\fC#include 'driver\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &out, const \fBPolynom\fP &p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Файл с реализацием методов класса \fBDriver\fP\&. 


.SH "Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & out, const \fBPolynom\fP & p)"
Перегрузка оператора << для вывода полинома в формате 'ПРИЗНАК_ПРИВОДИМОСТИ РАЗМЕРНОСТЬ_ПОЛЯ КОЭФФИЦИЕНТ КОЭФФИЦИЕНТ \&.\&.\&. КОЭФФИЦИЕНТ' 
.SH "Author"
.PP 
Generated automatically by Doxygen for Irreducible Polynomial from the source code\&.
