.TH "C:/Users/user/Desktop/irreducible-polynomial-doc/irreducible-polynomial-doc/source/driver/LibraryInterface/LibraryInterface.h" 3 "Fri Apr 29 2016" "Irreducible Polynomial" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Desktop/irreducible-polynomial-doc/irreducible-polynomial-doc/source/driver/LibraryInterface/LibraryInterface.h \- Заголовочный файл класса \fBLibraryInterface\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include '\&.\&./\&.\&./lib/lib\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLibraryInterface\fP"
.br
.RI "\fIКласс, предназначенный для подключения динамической бибилиотеки к приложению \fP"
.in -1c
.SH "Detailed Description"
.PP 
Заголовочный файл класса \fBLibraryInterface\fP\&. 

Данный файл содержит в себе определение класса, обеспечивающего вызов функций динамической библиотеки 
.SH "Author"
.PP 
Generated automatically by Doxygen for Irreducible Polynomial from the source code\&.
