.TH "C:/Users/user/Desktop/irreducible-polynomial-doc/source/lib/Polynom/polynom.h" 3 "Fri Apr 29 2016" "Irreducible Polynom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/user/Desktop/irreducible-polynomial-doc/source/lib/Polynom/polynom.h \- Заголовочный файл класса \fBPolynom\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPolynom\fP"
.br
.RI "\fIОписывает многочлен над конечным полем и основные операции над ним \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPolynomState\fP { \fBNEED_CHECK\fP = -1, \fBREDUCIBLE\fP = 0, \fBIRREDUCIBLE\fP = 1 }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Заголовочный файл класса \fBPolynom\fP\&. 

Данный файл содержит в себе определение класса обеспечивающего хранение полиномов над конечным полем, а так же функционал по работе с ними 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBPolynomState\fP"
Перечесление описывающее приводимость полинома NEED_CHECK - требует проверки полинома(состояние по умолчанию) REDUCIBLE - полином является приводимым IRREDUCIBLE - полином не прифодим 
.SH "Author"
.PP 
Generated automatically by Doxygen for Irreducible Polynom from the source code\&.
